apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: srvresolvers.amargher.io
spec:
  group: amargher.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                srvRecord:
                  type: string
                includeTXT:
                  type: boolean
  scope: Cluster
  names:
    plural: srvresolvers
    singular: srvresolver
    kind: SRVResolver
  
